spring:
  mail:
    host: smtp.yandex.ru
    username: valera.kudryavtsev.nsk@yandex.ru
    password: "bqiztjfisyvynodu" # специальный пароль для приложения (см. Яндекс Account)
    port: 465
    protocol: smtps
    test-connection: true # проверка подключения при старте приложения
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://yourscoremysqldb:3306/yourscore
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
cors:
  originPatterns: http://localhost:3000
football-api:
  token: fe382c8a16f0430ca32f601d38888099
jwt:
  secret-key: examplesupersecurekeyforencodinganddecodingtheHS256algorithm
  expiration-time: 86400000


